### ISSUE TITLE
Crear un Roadmap

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#16]
### Pendiente
- [x] Pasar las servilletas con notas a una serie de milestones
- [x] Asignar las tareas más obvias
- [x] Actualizar el backlog.md
