### ISSUE TITLE
Crear los milestones de la temporada y planificar tareas

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#38]
### Pendiente
- [ ] @ulisesGascon crear los milestones
- [ ] @ulisesGascon Subir las tareas acordadas a los sprints
- [ ] @ulisesGascon Mover/archivar tareas viejas/descontextualizades
