### ISSUE TITLE
Plan para tener la electronica

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#47]
Como la electronica en un tema complejo y ahora estamos ya aterrizando... 

Dejamos aquí el plan que se llevará para que sea más facil seguirlo

### P3
- [ ] Migrar `NODEMCU progresos` #37 al repo
- [ ] Definir los `Datos Finales` #45
- [ ] Hacer un `fake` con los rangos del coche y las rutas MQTT
- [ ] Cerrar la `Arquitectura` #46

### P4
- [ ] Instalar en el coche 
- [ ] @rubenmoreno94 migrar cada dato `fake` a sensores reales
